### ISSUE TITLE
mr.roboto does not send any mails to the CVS mailinglist if the package is not included in any buildout.coredev.

### ISSUE THREAD

**Issue by tisto** [plone/mr.roboto#11]
Core developers should be notified on any commits on core packages, not only the ones that are currently included in buildout.coredev (e.g. packages that are under development and not included yet).

**Comment by gforcada** [comment]
@tisto is this fixed already?

**Comment by gforcada** [comment]
Feel free to reopen with an example so it can be easier to fix, if it still happens.
