### ISSUE TITLE
Replace racially insensitive terms with neutral ones

### ISSUE THREAD

**Issue by stevepiercy** [plone/mr.roboto#113]
We use the terms "whitelisted" in this repo 27 times across 5 files. I would suggest replacing it with "allowlist".

I would also suggest renaming the default branch from `master` to `main`. That part is easy, but if you have a bunch of attached workflows, it may get complicated.

**Comment by gforcada** [comment]
Yes, `whitelisted` should get renamed 👍🏾 

branch name, indeed, workflows and a few other things might make not it that simple to rename the branch... and specially this repository that gets barely any attention is far from the most offending we should be renaming IMHO. We should do that for all plone packages (CMFPlone and such) which are much more highly visible, but again have plenty of workflows that rely on `master` being the branch 🤦🏾
