### ISSUE TITLE
Pull request merges do not trigger a Jenkins build.

### ISSUE THREAD

**Issue by tisto** [plone/mr.roboto#12]
Merging this pull request through the github web interface:

https://github.com/plone/plone.caching/pull/1

did not trigger a Jenkins build and there is nothing in the mr.roboto logs:

http://jenkins.plone.org/roboto/jobs

**Comment by gforcada** [comment]
I think this is already solved right? *now* that we commit on buildout.coredev on any change.

If not, feel free to reopen.
