### ISSUE TITLE
Ignore changes to pre-commit config?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/mr.roboto#120]
I thought we were already ignoring automated pre-commit changes that update the config, but we only [ignore the missing changelog entry](https://github.com/plone/mr.roboto/pull/114).  They are still added to `checkouts.cfg`, so we have 79 checkouts now...

Could we ignore those?
Can be tricky though, as they may contain changes in the code as well.  See for example this [fake commit](https://github.com/plone/buildout.coredev/commit/9e8ae50764eddac89c3cae58e6ca6e9eafb6c38b) which updates a template as well, likely done automatically by `zpretty`.

We should probably manually remove all of these, except the ones that change more than just the config.  Otherwise it takes long for Jenkins and locally to update all the checkout, and may give errors.  I have a `local.cfg` with `[buildout] mr.developer-threads = 1` otherwise GitHub times out for me after a while, even with a lot less checkouts.

If anyone starts doing that (@gforcada, @jensens ?), please ping me in the release-team channel, so we don't do duplicate work.

**Comment by gforcada** [comment]
Yes, it would be great idea to update `mr.roboto` to not update `buildout.coredev` if a PR gets merged from a `pre-commit` author 👍🏾 

Maybe in two weeks during the sprint I have some time 🍀

**Comment by jensens** [comment]
Would a `git push -o ci.skip` work to suppress certain actions here??

**Comment by gforcada** [comment]
That can be tricky to get it working 100% of the times... I have to have a look at the code

**Comment by gforcada** [comment]
Turns out it was not too difficult 🍀 see #123
