### ISSUE TITLE
Make it possible to avoid adding a package to checkouts.cfg

### ISSUE THREAD

**Issue by gforcada** [plone/mr.roboto#128]
A generalization of #123.

In general, though, specially with `plone/meta` still not being fully stabilized, it is desirable to not add plenty of checkouts on `buildout.coredev/checkouts.cfg` for PRs that only do changes related to `plone/meta` configuration updates.

This should be an advanced/hidden 🕵🏾 feature though, as in 99% of regular PRs we want that to happen.

A, hopefully easy solution might be that when a PR gets merged, a `[ci-skip]` message is added on the commit message (as GitHub allows to customize the merge commit message).

@davisagli @mauritsvanrees @fredvd Ideas/opinions? 🤔 🍀 

Thanks to @jensens work on the circular fixes, I'm preparing a few general fixes/improvements on `plone/meta` that would enable code coverage, circular dependencies detection and dependency checks that would be enabled globally.

If the changes do not introduce code changes, but only adding the required workflows and tox changes, we should not need to create a new release nor pollute `checkouts.cfg` IMHO. ♻️

**Comment by mauritsvanrees** [comment]
So the one doing the merge should remember to add `[ci skip]` to the merge commit in the GitHub UI?  That could work.  We will probably forget several times, but that should be no problem.

**Comment by gforcada** [comment]
I had the idea of using a specific label on PRs, but that seems to be a bit more complicated 😕 

The code in `mr.roboto` that makes commits on `buildout.coredev` to trigger the coredev Jenkins jobs only gets information about the commit that has been made (i.e. the merge commit) rather than the PR that got merged.

So the downside is that we can not use labels, but the upside is that the `[ci-skip]` in the merge commit message is already working 🎉
