### ISSUE TITLE
buildout.coredev commits do not trigger mr.roboto.

### ISSUE THREAD

**Issue by tisto** [plone/mr.roboto#13]
Those two commits did not trigger a Jenkins build:

https://github.com/plone/buildout.coredev/commit/5ee1e21afd7568aed24305ac23c61e7f7ae41dbe

https://github.com/plone/buildout.coredev/commit/a1993278862e64b931b1ca3e1b7dc1a8c78bd03c

There is nothing in the mr.roboto logs:

http://jenkins.plone.org/roboto/jobs

@bloodbare How can we debug these kind of problems? I have no idea which component is resposible...

**Comment by gforcada** [comment]
Most probably it is fixed with https://github.com/plone/mr.roboto/commit/921a5961beefff6fe22ac21c110e7779c9fedd91
