### ISSUE TITLE
Traceback after merging a PR

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/mr.roboto#156]
I merged some PRs, for example https://github.com/plone/Products.CMFPlone/pull/3861, but this did not end up as fake commit in coredev, neither in 6.0 nor 6.1.
On https://jenkins.plone.org/roboto/log (with token) I get a traceback with a ValueError:

```
Missing template asset: mr.roboto:templates/home.pt
(/srv/mr.roboto/lib/python3.11/site-packages/mr/roboto/templates/home.pt)
```

**Comment by gforcada** [comment]
It should be fixed, I realized it as well this morning when checking the `plone.app.content` PR I'm trying to get merged.

**Comment by mauritsvanrees** [comment]
Fix confirmed, thanks.
