### ISSUE TITLE
Watch for contributors

### ISSUE THREAD

**Issue by gforcada** [plone/mr.roboto#16]
One great thing of having mr.roboto monitoring our repositories is that we could instrument it to do all sort of things.

An easy one would be to report on any pull request whose committers are not members of the plone github organization. This way we will no longer have to waste our precious time on checking if a person is member or not. @jensens will be really appreciated at this one :-) Organizations like Openstack do this (they were doing it on github until they decided to move to their own infrastructure).

@polyester is the membership on plone github organization enough to know if someone has signed the contributors agreement?

**Comment by davisagli** [comment]
@gforcada specifically membership in the "Developers" team of the plone organization
