### ISSUE TITLE
Add packages to checkouts.cfg after a pull request merge

### ISSUE THREAD

**Issue by gforcada** [plone/mr.roboto#26]
It just happened to me right now:
- plone.app.multilingual had a pull request merged but it was not added to buildout.coredev checkouts.cfg
- I was hacking away at a PLIP job and all of a sudden, because I'm checking out p.a.multilingual master branch, my build is broken

mr.roboto already sends emails, but it would be much interesting/useful to also create a commit automatically on buildout.coredev to add the package on the checkouts list.

We already have code in place on mr.roboto to create commits on buildout.coredev and so far it has proved really useful and reliable, so let's remove an extra hassle to our developers and let's them just work on pull requests without having to deal with keeping checkouts.cfg updated.

@tisto @mauritsvanrees @esteele ideas/concerns?

**Comment by tisto** [comment]
We discussed this possibility. Though, we wanted to start simple and make sure the basics are working. I'd be ok with trying to make mr.roboto automatically add packages. Though, I'm not sure if mr.roboto can add a package before the job is actually started.

**Comment by gforcada** [comment]
If we take the ideal scenario:

- a user creates a pull request
- the pull request is tested on jenkins and end ups being green
- the user merges the pull request and is closed on github

At this point, github sends to mr.roboto a new update of that pull request telling that it has been merged, so we could easily create a new commit on buildout.coredev.

Manually merged branches and direct commits to master branches would not be covered (although they could be of course).

**Comment by mauritsvanrees** [comment]
I have been thinking this this might be good too. I recently went through most packages on 5.1 with one of the 'bin/manage' commands and found too many that were missing in checkouts.cfg. So +1 from me.
