### ISSUE TITLE
Create a branches overview

### ISSUE THREAD

**Issue by gforcada** [plone/mr.roboto#31]
Right now mr.roboto outputs both http://jenkins.plone.org/roboto/sources.json and http://jenkins.plone.org/roboto/checkouts.json

It would be really useful(?) to create a table view like:

package | 4.3 | 5.0 | 5.1
----------- | ---- | ---- | ----
CMFPlone | 4.3.x | 5.0.x | master
plone.app.blob | 1.3.x | master | master

... and so on.

This way it would be really easy to see to which plone release an specific package branch targets (in the example above p.a.blob master branch targets both 5.0 and 5.1).

Extra bonus would be to also use checkouts.json to mark which packages currently have changes and everything could be linked to github, so if actions are needed the links are there already.

@plone/framework-team @plone/release-team should that be useful or you have your own ways already?

**Comment by jensens** [comment]
additional the versions used could be placed somewhere. ``plone.versioncheck`` already has an html output which could be handy.

**Comment by gforcada** [comment]
@jensens if you mean getting the raw values that make this table you already have them available as json in http://jenkins.plone.org/roboto/sources.json

**Comment by jensens** [comment]
@gforcada i was referring to a different piece of information. Additional to sources.

**Comment by mauritsvanrees** [comment]
I run this gist before I release a Plone package, using information that I already have locally:
https://gist.github.com/mauritsvanrees/eb69adbb51747834808f6847c140b706
