### ISSUE TITLE
Build mockup docs

### ISSUE THREAD

**Issue by vangheem** [plone/mr.roboto#32]
The relevant commands for mockup are:

```
make bootstrap
make docs
cd mockup/docs
git add -A
git commit -a -m 'update docs build'
git push
```

**Comment by gforcada** [comment]
@vangheem you mentioned that this needs to be pushed to the gh-pages branch, so once you run these commands (on master banch) you need to switch branches and commit?

**Comment by vangheem** [comment]
No, the `make docs` command does the checkout of `gh-pages`.

**Comment by gforcada** [comment]
Oh, then even better

**Comment by gforcada** [comment]
Probably this is outdated... re-open if it is still relevant, and anyway, nowadays we can do it with GitHub Actions 🤖
