### ISSUE TITLE
Ignore commits with [ci skip] in the message

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/mr.roboto#37]
I am adding `[ci skip]` to pre and postrelease commits with zest.releaser, and am adding it manually to other minor commits, to avoid a Jenkins or Travis job just for a typo fix in the changelog.
It would be nice if mr.roboto would not add a code analysis comment for such a commit. See for example https://github.com/plone/borg.localrole/commit/e35a63817f8d1b63d299f040e2af3d91a10f3e00#commitcomment-18628365
Do you agree?

**Comment by gforcada** [comment]
I see your point, but at the same time, we are not only checking for code mistakes, but also MANIFEST.in errors or readme errors as well...

OTOH fixing/reverting a ci-skip commit should be trivial...

The patch though should be on jenkins.plone.org repository, as jenkins gets notifications from github directly without mr.roboto doing any man in the middle work.
