### ISSUE TITLE
A commit on plone.app.layout does only trigger the Python 2.7 job on the Plone 4.3 buildout, not the Python 2.6 job

### ISSUE THREAD

**Issue by tisto** [plone/mr.roboto#4]
This is the commit:

https://github.com/plone/plone.app.layout/commit/b58a2e21b18fbd533bef3157303d59dea2a1f76b

http://54.246.112.106/job/plone-4.3-python-2.7/1021/

was triggered, the "Plone 4.3 - Python 2.6" job was not.

**Comment by gforcada** [comment]
mr.roboto no longer triggers jenkins builds directly.

Feel free to reopen.
