### ISSUE TITLE
mr.robot does not trigger jobs when collective packages change

### ISSUE THREAD

**Issue by tisto** [plone/mr.roboto#6]
We have some collective packages in the coredev buildouts and we currently do not trigger a Jenkins job on changes. Therefore bugs can be introduced that are only discovered on a later build. We should either move/rename all collective packages that are used in coredev to the plone repo or make sure we monitor the collective as well.

**Comment by gforcada** [comment]
Monitoring the whole collective could be a bit too much for what's currently doing mr.roboto, if we enhance it to provide travis-like functionality that's another story... but back to the point:

Current 5.1 lists the following collective sources:
- **collective.elephantvocabulary**
- **collective.monkeypatcher**
- **icalendar**
- **Products.DateRecurringIndex**
- collective.js.jqueryui
- collective.xmltestreport
- i18ndude
- jquery.recurrenceinput.js
- plone.app.locales

In bold the ones that I think it make sense to monitor, the other ones are still used/have code that could break Plone?

I have to test it with real changes, but I have a working version to monitor them.

**Comment by gforcada** [comment]
That's in production right now, I just pushed and updated the hooks.
