### ISSUE TITLE
mr.robot does not send emails on 5.0 failures.

### ISSUE THREAD

**Issue by tisto** [plone/mr.roboto#7]
This commit

https://github.com/plone/plone.formwidget.recurrence/commit/be0b33570721604984db05f5dfa1012e9e7a44c5#commitcomment-4509915

triggered a 5.0 build:

http://jenkins.plone.org/job/plone-5.0-python-2.7/781/

that failed. Though, I did not receive an email. Is it possible that mr.robot currently does not send emails for failing coredev jobs?

**Comment by gforcada** [comment]
As mr.roboto only monitors github and does not interact with jenkins, this issue is already moved to jenkins.plone.org repo, see https://github.com/plone/jenkins.plone.org/issues/110.
