### ISSUE TITLE
Be able to recreate commit hooks on a single repo or organization

### ISSUE THREAD

**Issue by gforcada** [plone/mr.roboto#73]
Re-creating the hooks that help mr.roboto interact with github takes a lot of time, as there are lots of repositories both on plone as well as collective organizations.

For cases of new repositories, see plone.z3cform recently, having a way to only recreate the hooks on that specific repository would be quite a time saver.

**Comment by mauritsvanrees** [comment]
With the recent accidental removal of a few repos, and when we can only restore the git code and no hooks, this issue is active again.

On https://jenkins.plone.org/roboto/ we have a link to "Re-create GitHub commit hooks". Perhaps we could pass a package name? Code is in

**Comment by mauritsvanrees** [comment]
Accidentally clicked Close...
I meant to say: the code is in [`runhooks.py`](https://github.com/plone/mr.roboto/blob/5086e21f6be09883aedb2cc738139bd4d008c3e9/src/mr.roboto/src/mr/roboto/views/runhooks.py#L22).

**Comment by gforcada** [comment]
Yes, so far that's not possible, but indeed it would be great.

**Comment by gforcada** [comment]
We have a [function to update a single repository](https://github.com/plone/mr.roboto/blob/5086e21f6be09883aedb2cc738139bd4d008c3e9/src/mr.roboto/src/mr/roboto/views/runhooks.py#L59), we need to enable a parameter to be passed to it 🤔

**Comment by gforcada** [comment]
It seems that GitHub, for a while (I guess) allows organization level hooks, not sure if that would be good enough for us, as we don't want to trigger jenkins jobs on new commits in the `documentation` repository for example... 🤔 

Maybe as soon as we migrate to Jenkinsfile format it might be easier to filter when a job is triggered, and then we can enable an organization level one? 🤔
