### ISSUE TITLE
checkouts.cfg does not get updated anymore. Github token missing?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/mr.roboto#79]
When a PR is merged, the package should be added to `checkouts.cfg`, but this no longer happens.
Problem should be somewhere in the [`UpdateCoredevCheckouts` subscriber](https://github.com/plone/mr.roboto/blob/575e14f91b8ced37eac7619a7731686afa90b733/src/mr.roboto/src/mr/roboto/subscriber.py#L458). Looks okay at first glance, but maybe something is in the logs?

The last time the checkouts were successfully updated on 5.1 and 5.2, was on [23 January](https://github.com/plone/buildout.coredev/commit/3d56080f90e5dcd3b8c37c00dc9c7450cdd663f2). On 4.3 it was on [26 December](https://github.com/plone/buildout.coredev/commit/53853be03f7936bf7d3e97e1a1c3de1087734ef8) which may be correct: not many changes are coming in. On 6.0 we don't yet update the checkouts automatically.

So last success was 23 January.
Aha, a few days later @gforcada made several changes, so it could be caused by one of those. Mostly version pin updates, but there is one more likely candidate: PR #76 was merged, which uses GitHub token authentication.

@gforcada Is maybe something missing here? Does a new GitHub token need to be stored on the server, or passed along somehow?

I guess `production.ini` on the server needs to get the new `github_token` value, instead of `github_user` and `github_password`.

**Comment by gforcada** [comment]
That's supposed to be like that already, I will try to have a look

**Comment by gforcada** [comment]
@mauritsvanrees do you have a specific example where I can dig on the logs to see if there is a logged error? :thinking:

**Comment by mauritsvanrees** [comment]
`plone.app.content` is a recent example on 5.2:

- I made a PR: https://github.com/plone/plone.app.content/pull/193.
- This was merged by @jensens 7 days ago, it seems just by merging it in the GitHub UI: https://github.com/plone/plone.app.content/commit/b7406aa1389e83f26b3ee4ed1282912a984fa32f
- Result was this fake commit by mr.roboto, updating `last_commit.txt`: https://github.com/plone/buildout.coredev/commit/c4ec5ce6511c159bdcbf857dca6e14bb46c559ad
- But `plone.app.content` was not added to the checkouts.
- I manually added it to the checkouts later:
https://github.com/plone/buildout.coredev/commit/c0e79b6c5067b17ec6e2b9e2a7d1b95562fc5fdb

I did some commits yesterday with the help of `plone.releaser`, finding various packages with changes that were not in the checkouts. Those commits have the same message (`<package> has changes`) that `mr.roboto` would add, but without the `[fc]` for fake commit in front of it. For example this one: https://github.com/plone/buildout.coredev/commit/bedb2ba0c658424f619c14fc84bb2faa8192060f

**Comment by gforcada** [comment]
Thanks! I will try to have a look at night

**Comment by mauritsvanrees** [comment]
Traceback in the mr.roboto log:

```
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/subscriber.py", line 501, in run
    self.add_pacakge_to_checkouts(not_in_checkouts)
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/subscriber.py", line 518, in add_pacakge_to_checkouts
    self.make_commit(repo, version, user)
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/subscriber.py", line 534, in make_commit
    checkouts_cfg_file = repo.get_file_contents(filename, head_ref.object.sha)
AttributeError: 'Repository' object has no attribute 'get_file_contents'
```

**Comment by mauritsvanrees** [comment]
Fixed.
