### ISSUE TITLE
Disable KGS github notifications

### ISSUE THREAD

**Issue by tisto** [plone/mr.roboto#8]
The github notifications about the KGS jobs confuse people (because they don't know about the KGS jobs and they do not run reliably yet). I'd say we should disable those messages for now. The KGS was meant to be an experimental feature and we should not push those things to developers before they work reliably:

https://github.com/plone/plone.app.blob/commit/c26ae4fcee48266b2131b9ded86373f5649850af#commitcomment-4626571

**Comment by gforcada** [comment]
Just like #9, closing, feel free to reopen.
