### ISSUE TITLE
Clarify to `run jobs` after repo-local CI checks have passed

### ISSUE THREAD

**Issue by rpatterson** [plone/mr.roboto#84]
I've been using Plone's Jenkins through the `mister-roboto` bot comment `@jenkins-plone-org please run jobs` directive for some time, albeit as an infrequent contributor, and read that comment many times and I only just recently came to understand something that seems important to communicate to less familiar contributors.  Namely that's it's best to get the repo-specific CI checks (e.g. GitHub actions, Travis CI, etc.) to passing *and then* launch the much longer running Plone Jenkins jobs as a final check before seeking review.  It seems worthwhile to improve that bot comment to make this clear.

**Comment by gforcada** [comment]
Hi @rpatterson the comment message is at: https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L623 might you have a first go on the re-wording? 🙂

**Comment by rpatterson** [comment]
> Hi @rpatterson the comment message is at: https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L623 might you have a first go on the re-wording? slightly_smiling_face

Certainly happy to if I get the time, but I'm not sure when I might.  I mainly reported the issue just to get it down somewhere.  Feel free to close with a "Feel free to re-open if you want to tackle it" comment or manage this issue how you like.  If someone ever does get to this, your pointer to the exact line of code is very helpful knowledge transfer and will save them time, thanks!

**Comment by rpatterson** [comment]
May also want to consider [making it clearer](https://github.com/plone/plone.restapi/pull/1304#issuecomment-1002410507) how to find [the Plone Jenkins docs of r PR jobs](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job).
